### ISSUE TITLE
make sure truffle assert is correct when comparing bigNum to integers in JS

### ISSUE THREAD

**Issue by ameensol** [SpankChain/spankbank#5]
```
    const initialCurrentPeriod = await spankbank.currentPeriod()
    assert.equal(initialCurrentPeriod, 0)
```

the `initialCurrentPeriod` is a BigNum, and the test works properly, but I need to know with more certainty what truffle's assert library is doing under the hood to compare the numbers

**Comment by zitatende** [comment]
The Chai library's `assert.equal` uses `==` internally. [1]
Hence, the BigNumber object is converted to a primitive type, and we finally end up comparing two JS numbers.

While this works for reasonably small numbers, a cleaner and safer solution would be to convert any number involved immediately to a BigNumber, and then do all arithmetic and comparisons with BigNumber logic.
(Not to mention that `assert.equal( BigNumber(1), BigNumber(1) );` fails, because it's two different objects.)

There is a Chai plugin [2] that provides BigNumber assertions, but it only supports BDD style.
If that was inconvenient, I'd probably just write my own wrappers around BigNumber's comparison operators. 
Something along the lines of:

```javascript
const newWrapper = function( name, bigNumFunc ) {
  assert[ name ] = function( a, b, message ) {
    const x = BigNumber(a);
    const y = BigNumber(b);
    assert( bigNumFunc.call( x, y ), message );
  };
};

newWrapper( "bnequal", BigNumber().isEqualTo );
newWrapper( "bnless", BigNumber().isLessThan );  // and so on

// all these work with BigNumbers internally
assert.bnequal( BigNumber(1), BigNumber(1) );
assert.bnequal( BigNumber(1), 1 );
assert.bnless( "2", 3 );
```

As usual, care has to be taken to construct BigNumbers from strings rather than number literals, when the numbers involved are very large.

[1] http://www.chaijs.com/api/assert/#method_equal
[2] http://www.chaijs.com/plugins/chai-bignumber/

**Comment by jamesyoung** [comment]
updating tests to use `chai-bignumber` and `chai-as-promised`
